samples:
    - WH
    - ZH
    - ggF
    - VBF
    - ttH
    - WJetsLNu
    - TTbar
    - SingleTop
    - DYJets
    - WZQQ
    - Diboson
    - EWKvjets
    - Data
regions_sel:
    # put any "selection name: selection" here to store it in the templates    
    "SR1": (numberBJets_Medium_OutsideFatJets == 0) & (ReconVCandidateFatJetVScore > 0.9) & (fj_ParT_score > 0.9) & (met_pt > 30) & (fj_mass > 60) & (fj_mass < 120) & (fj_pt > 250) & (h_fj_pt > 250)
    "TopCR": (numberBJets_Medium_OutsideFatJets > 0) & (fj_mass > 40) & (met_pt > 30)  & (fj_pt > 250) & (h_fj_pt > 250)
    "WJetsCR": (numberBJets_Medium_OutsideFatJets == 0) & (fj_pt > 250) &  (h_fj_pt > 250) & (met_pt > 30) & ( (  fj_mass > 40 & fj_mass < 60  ) |  fj_mass > 120  ) 
   
samples_dir:
    "2018": /uscms/home/jieun201/nobackup/YOURWORKINGAREA/july20_systematics/

model_path: /uscms/home/jieun201/nobackup/YOURWORKINGAREA/model.onnx
